[ZSH] Add return code of failed command to prompt
If the previous command has failed, add its return code in red to the
prompt. With an emoji ;)

Based on  https://zenbro.github.io/2015/07/23/show-exit-code-of-last-command-in-zsh.html

diff --git a/zshprompt b/zshprompt
--- a/zshprompt
+++ b/zshprompt
@@ -141,9 +141,20 @@ git_prompt_string() {
   [ -n "$git_where" ] && echo " $GIT_PROMPT_PREFIX%{$fg[yellow]%}${git_where#(refs/heads/|tags/)}$(parse_git_ahead)$(parse_git_state)$GIT_PROMPT_SUFFIX"
 }
 
+# Check last exit code, and print a visual feedback for it
+# https://zenbro.github.io/2015/07/23/show-exit-code-of-last-command-in-zsh.html
+function check_last_exit_code() {
+  local LAST_EXIT_CODE=$?
+  if [[ $LAST_EXIT_CODE -ne 0 ]]; then
+    local EXIT_CODE_PROMPT=' '
+    EXIT_CODE_PROMPT+="%{$fg_bold[red]%}😮 $LAST_EXIT_CODE%{$reset_color%} "
+    echo "$EXIT_CODE_PROMPT"
+  fi
+}
+
 # precmd prints before every prompt output
 precmd() { t --prompt }
 
-PROMPT='%F{cyan}${_prompt_sorin_pwd}%f%(!. %B%F{red}#%f%b.)$(git_prompt_string)${editor_info[keymap]} '
+PROMPT='$(check_last_exit_code)%F{cyan}${_prompt_sorin_pwd}%f%(!. %B%F{red}#%f%b.)$(git_prompt_string)${editor_info[keymap]} '
 
 RPROMPT='%F{cyan}%t'
